apiVersion: v1
kind: Service
metadata:
  name: megalith-dispatcher
  labels:
    app: megalith-dispatcher
spec:
  ports:
  - port: 9001
  type: LoadBalancer
  selector:
    app: megalith-dispatcher   